load(":define_modules.bzl", "define_modules")

define_modules("pineapple", "consolidate")
define_modules("pineapple", "gki")

define_modules("sun", "consolidate")
define_modules("sun", "perf")

define_modules("canoe", "consolidate")
define_modules("canoe", "perf")

define_modules("vienna", "consolidate")
define_modules("vienna", "perf")

define_modules("malabar", "consolidate")
define_modules("malabar", "perf")

define_modules("shikra", "consolidate")
define_modules("shikra", "perf")

define_modules("autogvm", "consolidate")
define_modules("autogvm", "perf")

